api-version: '26.1'
name: UnitedBoats
version: 1.0.8-SNAPSHOT
main: org.unitedlands.boats.UnitedBoats
description: UnitedBoats anti-boat-lag plugin
load: STARTUP
authors:
- Theriel_
depend:
- UnitedLib
